# Generated by Django 5.1.2 on 2024-10-24 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('class_number', models.IntegerField()),
                ('student_number', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(default=datetime.datetime(2024, 10, 29, 15, 54, 26, 797614, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
