# Generated by Django 5.1.2 on 2024-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_rented_at_alter_rental_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='class_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rented_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='student_number',
            field=models.CharField(max_length=20),
        ),
    ]
